"""
Decoder module for converting GAN-generated packet representations to network protocol format.

This module handles the decoding of 28x28 matrix representations generated by the GAN
into IPv4 and protocol (UDP/ICMP) headers in hexadecimal format.
"""

import numpy as np

MATRIX_SIZE = 28  # Size of the generated image matrix
DOWNSCALE_FACTOR = 2  # Factor to reduce matrix dimensions
HEX_DIVISOR = 16  # Divisor for hexadecimal conversion
IPV4_HEADER_LENGTH = 20  # IPv4 header length in bytes
IPV4_PROTOCOL_OFFSET = 9  # Offset for protocol field in IPv4 header
UDP_PROTOCOL_ID = '11'  # Protocol ID for UDP
UDP_LENGTH_OFFSET = 24  # Offset for UDP length field
UDP_HEADER_SIZE = 8  # Size of UDP header
DEFAULT_PROTOCOL_END = 52  # Default end offset for non-UDP protocols
ICMP_PROTOCOL_END = 56  # End offset for ICMP protocol


def _downscale_matrix(raw_bytes, matrix_size=MATRIX_SIZE, factor=DOWNSCALE_FACTOR):
    """Downscale the input matrix by averaging blocks of pixels.
    
    Args:
        raw_bytes (numpy.ndarray): Raw bytes matrix from GAN output
        matrix_size (int): Size of the input matrix (default: 28)
        factor (int): Downscaling factor (default: 2)
        
    Returns:
        numpy.ndarray: Downscaled matrix
    """
    downscaled_size = matrix_size // factor
    packet = np.zeros((downscaled_size, downscaled_size), dtype=np.uint8)
    
    raw_bytes = np.array(raw_bytes).reshape((matrix_size, matrix_size))
    
    for i in range(0, matrix_size, factor):
        for j in range(0, matrix_size, factor):
            packet[i // factor, j // factor] = int(raw_bytes[i:i+factor, j:j+factor].mean())
    
    return packet


def _matrix_to_hex_list(packet, downscaled_size):
    """Convert downscaled matrix to list of hexadecimal byte strings.
    
    Args:
        packet (numpy.ndarray): Downscaled packet matrix
        downscaled_size (int): Size of the downscaled matrix
        
    Returns:
        list: List of hexadecimal byte strings
    """
    packet_hex_list = []
    
    for i in range(downscaled_size):
        for j in range(0, downscaled_size, DOWNSCALE_FACTOR):
            # Convert two adjacent values to a single hex byte
            high_nibble = hex(int(packet[i][j] / HEX_DIVISOR)).replace('0x', '')
            low_nibble = hex(int(packet[i][j+1] / HEX_DIVISOR)).replace('0x', '')
            packet_hex_list.append(high_nibble + low_nibble)
    
    return packet_hex_list


def _extract_protocol_data(packet_hex_list):
    """Extract IPv4 and protocol headers from hex list.
    
    Args:
        packet_hex_list (list): List of hexadecimal byte strings
        
    Returns:
        tuple: (ipv4_hex, protocol_hex) IPv4 and protocol headers as hex strings
    """
    ipv4_bytes = packet_hex_list[:IPV4_HEADER_LENGTH]
    
    protocol_type = packet_hex_list[IPV4_PROTOCOL_OFFSET]
    
    if protocol_type == UDP_PROTOCOL_ID:
        udp_length_bytes = packet_hex_list[UDP_LENGTH_OFFSET:UDP_LENGTH_OFFSET+2]
        udp_length_hex = ''.join(udp_length_bytes)
        udp_payload_length = int(udp_length_hex, 16) - UDP_HEADER_SIZE
        
        protocol_end = IPV4_HEADER_LENGTH + UDP_HEADER_SIZE + udp_payload_length
        protocol_end = min(protocol_end, len(packet_hex_list))
    else:
        protocol_end = ICMP_PROTOCOL_END
    
    protocol_bytes = packet_hex_list[IPV4_HEADER_LENGTH:protocol_end]
    
    ipv4_hex = ''.join(ipv4_bytes)
    protocol_hex = ''.join(protocol_bytes)
    
    return ipv4_hex, protocol_hex


def decode_packets(raw_bytes):
    """Decode GAN-generated packet representation to IPv4 and protocol headers.
    
    This function converts a 28x28 matrix representation of a network packet
    (generated by the GAN) into hexadecimal IPv4 and protocol headers suitable
    for PCAP file generation.
    
    Args:
        raw_bytes (numpy.ndarray): Raw bytes matrix from GAN output (28x28)
        
    Returns:
        tuple: (ipv4_header, protocol_header) where:
            - ipv4_header (str): IPv4 header as hexadecimal string
            - protocol_header (str): Protocol header (UDP/ICMP) as hexadecimal string
    """
    downscaled_size = MATRIX_SIZE // DOWNSCALE_FACTOR
    
    packet = _downscale_matrix(raw_bytes, MATRIX_SIZE, DOWNSCALE_FACTOR)
    
    packet_hex_list = _matrix_to_hex_list(packet, downscaled_size)
    
    ipv4_header, protocol_header = _extract_protocol_data(packet_hex_list)
    
    return ipv4_header, protocol_header